### ISSUE TITLE
Qualification script for GP-data uses CURRENTDATE instead of T-date

### ISSUE THREAD

**Issue by daanjo3** [Nictiz/Nictiz-STU3-testscripts#103]
In the [test script](https://github.com/Nictiz/Nictiz-STU3-testscripts/blob/master/FHIR3-0-2-MM202001-Cert/GenPractData-2-0/XIS-Server/medmij-gpdata-xis-1-1-serve-lab-diagn-observation-json.xml) for lab and diagnostic results of the GP qualification the wrong variable appears to be used.

Rather than using the T-date it appears to be using the current date: `ge${CURRENTDATE,M,-14}`. This is currently causing a qualification to fail, as the resources for that qualification use a T-date later than today.

**Comment by pieter-edelman-nictiz** [comment]
Hi @daanjo3 ,

My apologies that we didn't respond to this sooner, we don't actively use this issue tracker but we forgot to disable it. Could you submit this issue to our [BITS issue tracker](https://bits.nictiz.nl/projects/MM) (use the MM project for MedMij standards).
